name: jernal
description: A desktop journaling app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  floor: ^1.3.0
  provider: ^6.0.3
  package_info_plus: ^8.3.0
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  textf: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.3.0
  build_runner: ^2.1.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/google_fonts/
    