name: Run tests on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: "Generate AppLocalizations files"
        run: flutter gen-l10n
      - name: Build & run tests
        run: flutter test


  #build-and-release-linux:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: subosito/flutter-action@v1
  #      with:
  #        channel: 'stable'
  #        flutter-version: '2.10.0'
  #    - name: Install dependencies
  #      run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
  #    - name: Install project dependencies
  #      run: flutter pub get
  #    - name: Generate intermediates
  #      run: flutter pub run build_runner build --delete-conflicting-outputs
  #    - name: Enable linux build
  #      run: flutter config --enable-linux-desktop
  #    - name: "Generate AppLocalizations files"
  #      run: flutter gen-l10n
  #    - name: Build & run tests
  #      run: flutter test


  #build-and-release-windows:
  #  runs-on: windows-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: subosito/flutter-action@v1
  #      with:
  #        channel: 'stable'
  #        flutter-version: '2.10.0'
  #    - name: Install project dependencies
  #      run: flutter pub get
  #    - name: Generate intermediates
  #      run: flutter pub run build_runner build --delete-conflicting-outputs
  #    - name: Enable windows build
  #      run: flutter config --enable-linux-desktop
  #    - name: "Generate AppLocalizations files"
  #      run: flutter gen-l10n
  #    - name: Build & run tests
  #      run: flutter test